{
 "title": "Challenger 009",
 "time": { "from": "2024-05-26T16:36:39.092Z", "to": "2024-05-27T04:36:39.092Z" },
 "panels": [
  {
   "title": "Nginx Active Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Idle Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_waiting{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Connection Handled",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_handled{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Accepted Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_accepted{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histórico de conexiones activas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "nginx_connections_active{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histórico de conexiones procesadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "nginx_connections_handled{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histórico de peticiones HTTP totales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "nginx_http_requests_total{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje de uso de CPU actual",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=\"nginx-6bff48bf56-jzm2k\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histórico del uso de CPU del container nginx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "namespace_cpu:kube_pod_container_resource_requests:sum{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "namespace_cpu:kube_pod_container_resource_limits:sum{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histórico del uso de memoria del container nginx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_failcnt{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_max_usage_bytes{namespace=\"challenger-009\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}